### ISSUE TITLE
Typo Causes Keypair to Fail

### ISSUE THREAD

**Issue by ceramicowl** [saint-lascivious/unbound-config#2]
https://github.com/saint-lascivious/unbound-config/blob/69e9d11c1f1c30834f4bfaf60b7bacb23c19a833/remote-control.conf#L64

Presumably a simply typo, but line 64 should read `control-cert-file` rather than a second iteration of `control-key-file`.

**Comment by saint-lascivious** [comment]
solved in b44c2ec
